name: Build Vite site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout на кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build project
      - name: Build Vite
        run: npm run build

      # 5. Show dist folder
      - name: List dist folder
        run: ls -la dist
